# Assignment 1:
### - The automated_stat_analyzer Function
- Scenario: A retail company needs a utility to quickly summarize sales data. Students must create a function that identifies the 
"Central Tendency" and "Dispersion" of any numerical column.
- ### Requirements:

* Accept a Pandas DataFrame and a column name.

* Calculate the Mean, Median, and Standard Deviation .

* Identify if the data is "Skewed" by comparing the Mean and Median.


* Bonus: If the column is categorical, return the Mode instead.

### Your Data

In [1]:
import pandas as pd
import numpy as np

# Create a synthetic Company Sales Dataset
data = {
    'Transaction_ID': range(1, 11),
    'Product_Category': ['Electronics', 'Home', 'Electronics', 'Sports', 'Home', 
                         'Electronics', 'Home', 'Sports', 'Electronics', 'Electronics'],
    'Sales_Amount': [150, 200, 155, 300, 210, 180, 205, 1000, 190, 160], # 1000 is an Outlier
    'Customer_Age': [25, 34, np.nan, 45, 23, 31, 29, np.nan, 38, 40],    # Contains Nulls (NaN)
    'Rating': [5, 4, 3, 5, 2, 4, 5, 2, 4, 3]
}

df_test = pd.DataFrame(data)

# Save to CSV for students to practice loading files [cite: 74]
df_test.to_csv('company_sales_test.csv', index=False)
print("Test dataset created successfully!")

Test dataset created successfully!

In [2]:
df_test.head()

   Transaction_ID Product_Category  Sales_Amount  Customer_Age  Rating
0               1      Electronics           150          25.0       5
1               2             Home           200          34.0       4
2               3      Electronics           155           NaN       3
3               4           Sports           300          45.0       5
4               5             Home           210          23.0       2

In [3]:
import pandas as pd

def automated_stat_analyzer(df, column_name):
    col = df[column_name]
    
    if col.dtype == 'object':
        return {
            'Mode': col.mode()[0]
        }
    
    mean_val = col.mean()
    median_val = col.median()
    std_val = col.std()
    
    if mean_val > median_val:
        skew = "Right Skewed"
    elif mean_val < median_val:
        skew = "Left Skewed"
    else:
        skew = "Symmetrical"
        
    return {
        'Mean': mean_val,
        'Median': median_val,
        'Std': std_val,
        'Skewness': skew
    }

In [4]:
automated_stat_analyzer(df_test, 'Sales_Amount')

{'Mean': 275.0,
 'Median': 195.0,
 'Std': 258.30645021412494,
 'Skewness': 'Right Skewed'}

In [5]:
import pandas as pd

def automated_stat_analyzer(df, column_name):
    col = df[column_name]
    
    if col.dtype == 'object' or pd.api.types.is_categorical_dtype(col):
        return {
            'Mode': col.mode()[0]
        }
    
    mean_val = col.mean()
    median_val = col.median()
    std_val = col.std()
    
    if mean_val > median_val:
        skew = "Right Skewed"
    elif mean_val < median_val:
        skew = "Left Skewed"
    else:
        skew = "Symmetrical"
        
    return {
        'Mean': mean_val,
        'Median': median_val,
        'Std': std_val,
        'Skewness': skew
    }

In [6]:
automated_stat_analyzer(df_test, 'Product_Category')

{'Mode': 'Electronics'}

## Assignment 2: 
  ### The null_handling_strategy Function

#### Scenario: Incoming user data often has missing values.Students must implement a flexible strategy to handle these "Null Values" to prepare data for Machine Learning.
### Requirements:

* Check for null values in the DataFrame.

* Apply a strategy based on parameters: "drop_rows", "fill_mean", or "fill_median" .

* Ensure the function only fills numerical columns when using mean or median.

In [7]:
import pandas as pd
import numpy as np

def null_handling_strategy(df, strategy="fill_mean"):
    df_cleaned = df.copy()
    
    if strategy == "drop_rows":
        return df_cleaned.dropna()
    
    elif strategy == "fill_mean":
        numeric_cols = df_cleaned.select_dtypes(include=[np.number]).columns
        df_cleaned[numeric_cols] = df_cleaned[numeric_cols].fillna(df_cleaned[numeric_cols].mean())
        return df_cleaned
        
    elif strategy == "fill_median":
        numeric_cols = df_cleaned.select_dtypes(include=[np.number]).columns
        df_cleaned[numeric_cols] = df_cleaned[numeric_cols].fillna(df_cleaned[numeric_cols].median())
        return df_cleaned

In [8]:
null_handling_strategy(df_test, strategy="fill_mean")

   Transaction_ID Product_Category  Sales_Amount  Customer_Age  Rating
0               1      Electronics           150        25.000       5
1               2             Home           200        34.000       4
2               3      Electronics           155        33.125       3
3               4           Sports           300        45.000       5
4               5             Home           210        23.000       2
5               6      Electronics           180        31.000       4
6               7             Home           205        29.000       5
7               8           Sports          1000        33.125       2
8               9      Electronics           190        38.000       4
9              10      Electronics           160        40.000       3

In [9]:
df_mean = null_handling_strategy(df_test, strategy="fill_mean")
df_mean[['Customer_Age']]

   Customer_Age
0        25.000
1        34.000
2        33.125
3        45.000
4        23.000
5        31.000
6        29.000
7        33.125
8        38.000
9        40.000

In [10]:
df_median = null_handling_strategy(df_test, strategy="fill_median")
df_median[['Customer_Age']]

   Customer_Age
0          25.0
1          34.0
2          32.5
3          45.0
4          23.0
5          31.0
6          29.0
7          32.5
8          38.0
9          40.0

In [11]:
df_dropped = null_handling_strategy(df_test, strategy="drop_rows")
df_dropped

   Transaction_ID Product_Category  Sales_Amount  Customer_Age  Rating
0               1      Electronics           150          25.0       5
1               2             Home           200          34.0       4
3               4           Sports           300          45.0       5
4               5             Home           210          23.0       2
5               6      Electronics           180          31.0       4
6               7             Home           205          29.0       5
8               9      Electronics           190          38.0       4
9              10      Electronics           160          40.0       3