In [1]:
pip install numpy

Requirement already satisfied: numpy in c:\users\moham\anaconda3\lib\site-packages (1.26.4)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np

In [3]:
s = np.array(5)
print(s)
print("=============")
v = np.array([1,2,3,4])
print(v)
print("=============")
m = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(m)

5
=============
[1 2 3 4]
=============
[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [4]:
s = np.array(5)
print(s.ndim)
print(s.shape)
print("=============")
v = np.array([1,2,3,4])
print(v.ndim)
print(v.shape)
print("=============")
m = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(m.ndim)
print(m.shape)

0
()
=============
1
(4,)
=============
2
(3, 3)

In [5]:
vec =np.array([1,2,3,4,5,6])
mat = vec.reshape(3,2)
mat.shape[0]

3

In [6]:
vec =np.array([1,2,3,4])
mat=vec.reshape(vec.shape[0],1)
print(mat)

[[1]
 [2]
 [3]
 [4]]

In [7]:
def array_reshape(arr, rows, cols):
    try:
        arr = np.array(arr)
        return arr.reshape(rows, cols)
    except (TypeError, ValueError) as e:
        raise ValueError(f"invalid reshape operation:(e)")

In [8]:
vec = [1,2,3,4,5,6]
array_reshape(vec, 2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#object -->string -->float -->int -->bool
mat = np.array([[1,2,3],
                [4,5.5,6],
                [7,8,9]])
print(mat.dtype)

float64

In [10]:
import numpy as np

In [11]:
def m_init(shape,value =0):
    return np.full(shape,value)

m_init((3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [12]:
import pandas as pd

In [13]:
s = pd.Series([1,2,3,4,5])

In [14]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [15]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]

# data = {'col1':[1,2,3,4],
#         'col2':[444,555,666,444],
#         'col3':['abc','def','ghi','xyz']}

In [16]:
columns = ["col1","col2","col3"]
df = pd.DataFrame(data,columns=["col1","col2","col3"])
display(df)
df.columns = ["id","sal","dep"]
df.index = ["d1","d2","d3","d4"]
display(df)

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

    id  sal  dep
d1   1  444  abc
d2   2  555  def
d3   3  666  ghi
d4   4  444  xyz

In [17]:
df.dtypes

id      int64
sal     int64
dep    object
dtype: object

In [18]:
df.dep.dtype

dtype('O')

In [19]:
df['dep'] = df['dep'].astype('category')

In [20]:
df.dtypes

id        int64
sal       int64
dep    category
dtype: object

In [21]:
cols_cat = ['id','sal']
df[cols_cat] = df[cols_cat].astype('category')

In [22]:
df.dtypes

id     category
sal    category
dep    category
dtype: object

In [23]:
df.head()

   id  sal  dep
d1  1  444  abc
d2  2  555  def
d3  3  666  ghi
d4  4  444  xyz

In [24]:
df.tail()

   id  sal  dep
d1  1  444  abc
d2  2  555  def
d3  3  666  ghi
d4  4  444  xyz

In [25]:
df.columns

Index(['id', 'sal', 'dep'], dtype='object')

In [26]:
df.sal.unique()

[444, 555, 666]
Categories (3, int64): [444, 555, 666]

In [27]:
classification = df.sal.nunique()
classification

3

In [29]:
columns = ["col1","col2","col3"]
df = pd.DataFrame(data,columns=["col1","col2","col3"])
display(df)
df.index = ["d1","d2","d3","d4"]
display(df)

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

    col1  col2 col3
d1     1   444  abc
d2     2   555  def
d3     3   666  ghi
d4     4   444  xyz

In [30]:
def get_range(df):
    return df.max() - df.min()
get_range(df.col1)

3

In [31]:
df.col2.value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, d1 to d4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      int64
 2   col3    4 non-null      object
dtypes: int64(2), object(1)
memory usage: 128.0+ bytes

In [37]:
x1 = df.col2.values
type(x1)

numpy.ndarray

In [38]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'ghi'],
       [4, 444, 'xyz']], dtype=object)

In [43]:
df.replace(555,"Mohamed")

    col1     col2 col3
d1     1      444  abc
d2     2  Mohamed  def
d3     3      666  ghi
d4     4      444  xyz